name: Deploy to AWS S3

on:
    push:
        branches:
            - main # Deploy on push to the main branch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18' # Use the version matching your project
                  # cache: 'npm'

            # Step 3: Install dependencies
            - name: Install dependencies
              run:  cd client && npm install

            # Step 4: Build the project
            - name: Build project
              run: cd client && npm run build

            # Step 5: Configure AWS CLI
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-north-1 # Replace with your bucket's region

            # Step 6: Deploy to S3
            - name: Deploy to S3
              run: npm run deploy
